export const GET_CAMERAS = 'GET_CAMERAS'
export const ADD_CAMERA = 'ADD_CAMERA'
export const DELETE_CAMERA = 'DELETE_CAMERA'

export const GET_PHOTOS = 'GET_PHOTOS'
export const ADD_PHOTO = 'ADD_PHOTO'
export const DELETE_PHOTO = 'DELETE_PHOTO'

export const GET_REVIEWS = 'GET_REVIEWS'
export const ADD_REVIEW = 'ADD_REVIEW'

export const GET_PHOTOGRAPHERS = 'GET_PHOTOGRAPHERS'
export const ADD_PHOTOGRAPHER = 'ADD_PHOTOGRAPHER'
